from dataclasses import dataclass, field
from pathlib import Path


@dataclass
class Config:
    # Bag (ROS2 .db3 or directory)
    bag_path: str = "/mnt/data/your_bag.db3"
    lidar_topic: str = "/os_cloud_node/points"   # NTU VIRAL default
    camera_topic: str = "/camera/image_raw"       # set "" if no camera
    imu_topic: str = "/imu/imu"

    output_dir: str = "/mnt/data/semantic_output"

    # Poses (TUM format) — generated by SLAM before running this pipeline
    poses_file: str = ""

    # Frame sampling
    lidar_every_n: int = 10
    max_frames: int = 300

    # SAM
    sam_checkpoint: str = "/mnt/data/sam_vit_h_4b8939.pth"
    sam_model_type: str = "vit_h"    # vit_h | vit_l | vit_b

    # CLIP
    clip_model: str = "ViT-B/32"

    # BLIP-2 (optional — set False to skip captions, saves ~5GB VRAM)
    use_blip: bool = False

    # Graph
    graph_file: str = "/mnt/data/semantic_output/semantic_graph.pkl"
    spatial_edge_dist: float = 5.0    # metres
